"""Canonical Phase 10 hands-free wake phrase and official model identity."""

from __future__ import annotations

PRIMARY_WAKE_PHRASE = "Hey Jarvis"
PRIMARY_WAKE_TOKENS = ("hey", "jarvis")

OPENWAKEWORD_MODEL_FILENAME = "hey_jarvis_v0.1.onnx"
OPENWAKEWORD_MODEL_REPOSITORY = "https://github.com/dscripka/openWakeWord"
OPENWAKEWORD_MODEL_REVISION = "v0.5.1"
OPENWAKEWORD_MODEL_COMMIT = "1eec2158c5c54150ac5f4c15065adacb1003b1e7"
OPENWAKEWORD_MODEL_SHA256 = "94a13cfe60075b132f6a472e7e462e8123ee70861bc3fb58434a73712ee0d2cb"
# The engine code is Apache-2.0; upstream states that pretrained model
# artifacts are CC BY-NC-SA 4.0 because of their training-data provenance.
OPENWAKEWORD_MODEL_LICENSE = "CC-BY-NC-SA-4.0"
OPENWAKEWORD_RUNTIME = "openwakeword==0.6.0; onnxruntime"

MICROWAKEWORD_MODEL_FILENAME = "hey_jarvis.tflite"
MICROWAKEWORD_MODEL_REPOSITORY = "https://github.com/esphome/micro-wake-word-models"
MICROWAKEWORD_MODEL_REVISION = "main"
MICROWAKEWORD_MODEL_COMMIT = "05b65922cc433c9df13e98e32a7fe520758c837e"
MICROWAKEWORD_MODEL_SHA256 = "21a7976add39ee24ec96c63d96b7aaa18e24d1d9824b963e451da8feb4b78b77"
MICROWAKEWORD_MODEL_GIT_BLOB = "0075302434cc72a460ced0b8f6c09c69214e5cf0"
MICROWAKEWORD_MODEL_LICENSE = "Apache-2.0 collection license; artifact-specific terms not declared"
MICROWAKEWORD_RUNTIME = "pymicro-wakeword==2.4.1; pymicro-features==2.0.2"


__all__ = [
    "MICROWAKEWORD_MODEL_COMMIT",
    "MICROWAKEWORD_MODEL_FILENAME",
    "MICROWAKEWORD_MODEL_GIT_BLOB",
    "MICROWAKEWORD_MODEL_LICENSE",
    "MICROWAKEWORD_MODEL_REPOSITORY",
    "MICROWAKEWORD_MODEL_REVISION",
    "MICROWAKEWORD_MODEL_SHA256",
    "MICROWAKEWORD_RUNTIME",
    "OPENWAKEWORD_MODEL_COMMIT",
    "OPENWAKEWORD_MODEL_FILENAME",
    "OPENWAKEWORD_MODEL_LICENSE",
    "OPENWAKEWORD_MODEL_REPOSITORY",
    "OPENWAKEWORD_MODEL_REVISION",
    "OPENWAKEWORD_MODEL_SHA256",
    "OPENWAKEWORD_RUNTIME",
    "PRIMARY_WAKE_PHRASE",
    "PRIMARY_WAKE_TOKENS",
]
